server:
  port: 8081
spring:
  datasource: #配置数据库连接
    username: root
    password: 123456
    url: jdbc:mysql://172.16.0.170:3306/order?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq: #配置rabbitmq
    host: 127.0.0.1
    port: 15672
    username: guest
    password: guest
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.order.entity
logging:
  level:
    com.example.order.mapper: debug
# 配置pagehelper分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

